# Generated by Django 3.0.dev20190414141414 on 2019-06-15 08:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('email', models.EmailField(blank=True, max_length=254)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.IntegerField()),
                ('company', models.CharField(blank=True, max_length=150)),
                ('GST', models.CharField(blank=True, max_length=100)),
                ('phone_number', models.IntegerField()),
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('Order_id', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('total_price', models.IntegerField()),
                ('Status', models.IntegerField(choices=[('0', 'In Progress'), ('1', 'succcess'), ('2', 'fail')], default='0')),
            ],
        ),
    ]
